
spring:
  application:
    name: expense_tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker_exp
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
